[package]
name = "rust2py"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]

[lib]
name = "rust2py"
crate-type = ["dylib"]

[dependencies]
cpython = { git = "https://github.com/dgrunwald/rust-cpython.git" }
